### ISSUE TITLE
Images on Amazon AWS

### ISSUE THREAD

**Issue by memowe** [learnyouahaskell/learnyouahaskell.github.io#12]
Some images seem to be included in `docs`, but many are still linked to `amazonaws.com`. I think it would be a good idea to include the complete artwork in the repository. Are there any legal/copyright issues preventing us from doing so?

If not, I could help with that. :)

**Comment by memowe** [comment]
I already did the first steps in [my own branch](https://github.com/learnyouahaskell/learnyouahaskell.github.io/compare/main...memowe:external-images), but it's better to wait for #17 to be merged. :)

I still don't know anything about the legal situation here.

**Comment by smith558** [comment]
Hi! Thanks for pointing this out, I was actually in the progress of transforming the links to point to locally stored copies pulled from AWS CDN. Didn't get very far yet. Thanks for taking the effort and making changes yourself! 🙂

**Comment by smith558** [comment]
Regarding the legality regarding storing the images locally. They're covered under the [CC BY-NC-SA 3.0](https://creativecommons.org/licenses/by-nc-sa/3.0/) Creative Commons license as the rest of the work so that is okay.

**Comment by smith558** [comment]
@memowe happy to merge your branch on this issue if you have one!

**Comment by memowe** [comment]
Yep, as #17 was merged, I will try to come up with something soon. :)
