### ISSUE TITLE
Replace Comments about BMI

### ISSUE THREAD

**Issue by andrewthad** [learnyouahaskell/learnyouahaskell.github.io#3]
The `syntax-in-functions` page includes a BMI example that may benefit from being rewritten. The two options I'm aware of would be:

* Keeping using BMI as the example, but change the messages for different categories
* Change the example to something else that uses division, perhaps calculating speed from distance and time, and then it would be possible to provide silly messages that aren't about a sensitive issue.

I prefer the second option because I think it would just be best to avoid discussing BMI. I am happy to put together a PR if the maintainer agrees.

**Comment by smith558** [comment]
@andrewthad Thanks for pointing this out! Yes, please feel free to fork and submit a PR. Pull requests are always welcome. ( and preferred 😇 )

**Comment by smith558** [comment]
one case here: https://learnyouahaskell.github.io/syntax-in-functions.html#let-it-be

![image](https://user-images.githubusercontent.com/44023416/154745889-029ac197-9f70-4a4f-be2d-c34566dff165.png)

**Comment by ulysses4ever** [comment]
@andrewthad you mentioned you were interested in submitting a PR. I think it would be a great improvement. I just bumped into another [SO question](https://stackoverflow.com/q/72940257/465100) about this terrible example.

I'm leaning towards your option 2 (do away with BMI altogether).
