### ISSUE TITLE
Typos in text

### ISSUE THREAD

**Issue by smith558** [learnyouahaskell/learnyouahaskell.github.io#6]
## Please report text typos here
typo 1
![image](https://user-images.githubusercontent.com/44023416/153909518-bf4fdb2d-36bb-48c7-b644-f26002c8891b.png)

@ https://learnyouahaskell.github.io/input-and-output.html#exceptions

**Comment by samtygier** [comment]
In For a Few Monads More > Reader? Ugh, not this joke again.
`If don't get how >>= works at this point` -> `If you don't get how >>= works at this point`
(Possibly `get` -> `understand` would make it a bit clearer).

**Comment by smith558** [comment]
@samtygier Thanks for the report! Mind making the correction and opening a PR? Would be greatly appreciated! 🙂

**Comment by smith558** [comment]
This seems like the best change for me:
If **you** don't **understand** how >>= works at this point

**Comment by maueroats** [comment]
All edits except the first one mentiond have already been made in the source.

With PR #55, this issue can be closed.

**Comment by memowe** [comment]
> With PR #55, this issue can be closed.

Allright, thanks everyone! :)
